### PR TITLE
Vault decrypt on PRs

### PR DESCRIPTION
**Pull request by nitay**
(copied from #1, accidentally made that one from our master)

Add support for decrypting ansible vault files in pull requests.
Requires diff to be of the format:

```
$ANSIBLE_VAULT;1.1;AES256
- 74533475
- 98743598
+ 23498234
+ 63749802
```
Specifically the vault header, followed by entire old file, followed by entire new file. I can make a follow up PR to also support complete delete / new file add as well.

I wrote all this in ES6 class format, hopefully that's kosher with you - found it much cleaner / easier to grok.

Caveats:
- Only works for Unified mode, so I removed the button to select Split mode
- Commenting not supported. Adding the button to enable comments is pretty easy I figured out how to do that, but the hard part is once someone writes a comment, having to pick it up the whole thread and displaying old comments after decrypting. So for now I just disabled comments.

### CODE REVIEW

**Comment by gwatts** [comment]
Thanks for making those changes @nitay - this is looking really good!

One oddity I'm seeing is my diffs often show a trailing delete and addition of a blank line with a lot of spaces, even though i've confirmed `removed` and `added` don't have any trailing blank lines, but do end with a newline.

If I run both of those through `.trim()` prior to feeding into `.diff_lines()` i get the correct result - have you seen something similar?

**Comment by gwatts** [comment]
screen shot 2017-03-16 at 11 03 53 am

**Comment by nitay** [comment]
I did see that once but haven't seen since. here's version with the trim(), try this lmk

**Comment by nitay** [comment]
@gwatts this should be ready to go, lmk what you think

**Comment by gwatts** [comment]
seeing some odd behaviour whereby diff shows the last line of the file has changed when it actually hasn't.... i'll dig in further tomorrow if you don't get there first

**Comment by gwatts** [comment]
@nitay Figured out the problem; not related to your code at all, so i'll address it in a separate commit.

Can you squash all these commits together with a more useful commit message and i'll merge it into master

Thanks

**Comment by nitay** [comment]
you can do the squash + merge as part of pushing the PR no?

**Comment by gwatts** [comment]
ah yep; didn't see the part where it would let you re-write the crappy default commit message.

**Comment by nitay** [comment]
excellent! let me know when google store is updated?

**Comment by gwatts** [comment]
yep - i've pushed it up to the store, currently waiting for Google to finish pushing it to their servers.. should be done within an hour.

**Comment by gwatts** [comment]
It's live now :-)

**Comment by nitay** [comment]
perfect thx!

**Comment by gwatts** [comment]
np - thanks for your patience; this is really a great addition to the extension

**Pull request merged**
